version: "3.9"

services:
  db_users:
    container_name: lab8
    ports:
      - 5430:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: lab8
    image: postgres:16.2
    
  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
